version: "3.9"
services:
  web-server:
    build: vulnerable-application
    ports:
      - "8080:8080"
  ubuntu:
    build: ubuntu


  exploit:               #http://localhost:8001/Evil.class
    build: log4shell-exploit
    ports:
      - "8001:8000"
      - "9999:9999"
  reverse-shell:         #http://localhost:8000/Exploit.class
    build: reverse-shell
    ports:
      - "8000:8000"
      - "1389:1389"

